-- Decorra seed: 12 styles (5 India-first) + model registry. Safe to re-run.

insert into styles (slug, name, region, tagline, details, negative, palette, sample_image, sort) values
('modern-indian', 'Modern Indian', 'india',
 'Clean lines with handcrafted Indian accents',
 'clean-lined sheesham wood furniture, block-print cushions, cane and rattan accents, terracotta and indigo accents, brass table lamp, handwoven dhurrie rug',
 'western fireplace', array['#8B5A2B','#C1440E','#2E3A87','#F3E9DC','#D4A373'], '/samples/modern-indian-living-room.webp', 10),
('kerala-traditional', 'Kerala Traditional', 'india',
 'Teak, red oxide and brass warmth',
 'teak wood furniture, red oxide floor, brass lamps and uruli with floating flowers, jute rug, wooden ceiling rafters look, warm natural light',
 'western fireplace, carpeted floor', array['#6B3E26','#B5651D','#8E2B1E','#F2E3C6','#C9A227'], '/samples/kerala-traditional-living-room.webp', 20),
('chettinad', 'Chettinad', 'india',
 'Athangudi tiles and carved heritage wood',
 'Athangudi tile patterned floor, carved dark wooden pillars look, antique brass vessels, Burma teak furniture, deep red and ochre palette, egg-plaster white walls',
 'modern glass furniture', array['#7A1F1F','#C68B2C','#2B2B2B','#F5F0E6','#1F5E5B'], '/styles/chettinad.svg', 30),
('rajasthani', 'Rajasthani', 'india',
 'Jewel tones, jharokha arches and mirror work',
 'carved jharokha-style mirror, block-printed textiles, mirror-work cushions, jewel-tone colours of fuchsia, saffron and turquoise, brass and camel-bone inlay side tables, low floor seating',
 'minimalist bare decor', array['#C2185B','#F57C00','#00897B','#FFF3E0','#B8860B'], '/styles/rajasthani.svg', 40),
('indo-contemporary', 'Indo-Contemporary', 'india',
 'Neutral calm with handloom soul',
 'neutral warm walls, low wooden seating, handloom textiles, one statement Indian art piece, cane pendant, warm layered lighting, indoor plants in terracotta pots',
 'clutter', array['#EDE6DB','#A67B5B','#5C4033','#6B8F71','#D9C5A0'], '/styles/indo-contemporary.svg', 50),
('japandi', 'Minimal Japandi', 'global',
 'Light oak, linen and quiet space',
 'light oak furniture, low profile seating, linen upholstery, beige and sage palette, paper lantern light, minimal decor',
 'clutter, bright colours', array['#E8E1D5','#B9A68C','#7D8B6A','#4A4A48','#FAF8F4'], '/samples/japandi-bedroom.webp', 60),
('scandinavian', 'Scandinavian', 'global',
 'Bright, airy and practical',
 'white walls, light ash wood, grey fabric sofa, simple pendant lights, wool throw, plants',
 'dark heavy furniture', array['#FFFFFF','#D8D2C4','#9AA5A8','#3E4A4F','#C8B99A'], '/styles/scandinavian.svg', 70),
('modern-luxe', 'Modern Luxe', 'global',
 'Velvet, marble and brass',
 'velvet sofa, marble surfaces, brushed brass details, layered warm lighting, large abstract art',
 'rustic wood', array['#1F2A44','#C9B37E','#E9E4DC','#6D6875','#2F2F2F'], '/styles/modern-luxe.svg', 80),
('industrial', 'Industrial', 'global',
 'Metal, leather and raw textures',
 'dark metal frames, cognac leather seating, exposed-bulb pendants, concrete-look surfaces, reclaimed wood shelves',
 'pastel colours', array['#3A3A3A','#8C5A3C','#A8A29E','#D6D3D1','#1C1917'], '/styles/industrial.svg', 90),
('bohemian', 'Bohemian', 'global',
 'Layered, eclectic and plant-filled',
 'layered patterned rugs, rattan chairs, macrame wall hangings, many plants, floor cushions, warm string lights',
 'sterile minimal', array['#B5651D','#E07A5F','#81B29A','#F2CC8F','#3D405B'], '/styles/bohemian.svg', 100),
('coastal', 'Coastal', 'global',
 'Breezy whites and sea blues',
 'whitewashed wood, linen slipcovered sofa, blue and sand palette, jute rug, rattan pendant, light sheer curtains',
 'dark heavy decor', array['#FFFFFF','#A7C7E7','#2E5E8C','#E8DCC4','#C2B280'], '/styles/coastal.svg', 110),
('mid-century', 'Mid-Century', 'global',
 'Walnut curves and retro colour',
 'walnut furniture with tapered legs, mustard and teal accents, sputnik chandelier, geometric rug',
 'ornate carvings', array['#6F4E37','#E1AD01','#1B6B6F','#E27D60','#F4EBD9'], '/styles/mid-century.svg', 120)
on conflict (slug) do update set
  name = excluded.name, region = excluded.region, tagline = excluded.tagline,
  details = excluded.details, negative = excluded.negative, palette = excluded.palette,
  sample_image = excluded.sample_image, sort = excluded.sort;

-- Model registry. Pick the render winner from the Replicate playground spike and set active accordingly.
delete from model_configs;
insert into model_configs (purpose, provider, model_ref, params, active) values
('render', 'replicate', 'black-forest-labs/flux-kontext-pro',
 '{"aspect_ratio":"match_input_image","output_format":"jpg","safety_tolerance":2}', true),
('render', 'replicate', 'adirik/interior-design',
 '{"guidance_scale":15,"num_inference_steps":50}', false),
('vision', 'anthropic', 'claude-sonnet-5', '{"max_tokens":1024,"temperature":0}', true),
('vision', 'google', 'gemini-2.5-flash', '{"temperature":0}', false);
